### ISSUE TITLE
BCAP Smile is visible even when not scrolling

### ISSUE THREAD

**Issue by BarryCap** [BarryCap/BarryCap.github.io#24]
**The BCAP Smile is visible even when not scrolling**, when the site is in full screen for example.

**Comment by BarryCap** [comment]
`min-height` of `div` was set to `100vh` without `padding` instead of `94vh` with `padding-top: 11px`.
````css
div {
  padding-top: 11px;
  min-height: 94vh; /* to fix footer */
}
````
was replaced by
````css
div {
  min-height: 100vh; /* to fix footer */
}
````
