### ISSUE TITLE
Clean up CSS

### ISSUE THREAD

**Issue by BarryCap** [BarryCap/BarryCap.github.io#54]
Order CSS properties (in `styles.css`) in a specific order. Like the [Concentric CSS](https://rhodesmill.org/brandon/2011/concentric-css/):
```css
{
    display: ;    /* Where and how the box is placed */
    position: ;
    float: ;
    clear: ;

    visibility: ; /* Can the box be seen? */
    opacity: ;
    z-index: ;

    margin: ;     /* Layers of the box model */
    outline: ;
    border: ;
    background: ;
    padding: ;

    width: ;      /* Content dimensions and scrollbars */
    height: ;
    overflow: ;

    color: ;      /* Text */
    text: ;
    font: ;
}
```
It would be great to have it automated but I don't think it's possible…

The full method is here → [Concentric-CSS-Complete](https://github.com/BarryCap/BarryCap.github.io/files/6496981/concentric.txt) (from [style3.css](https://github.com/brandon-rhodes/Concentric-CSS/blob/master/style3.css))
